# Generated by Django 5.2.6 on 2025-09-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
