# Generated by Django 5.2.6 on 2025-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
